[project]
name = "metaphorical-emotion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "huggingface-hub>=1.4.0",
    "kagglehub>=0.4.2",
]
